### PR TITLE
[API-704] Wrap models, for easy selection

### PR DESCRIPTION
**Pull request by billkauf**
https://pagerduty.atlassian.net/browse/API-704

In order to replace a polymorphic model with all its alternatives, I need to wrap the model (in a `<span class="model">`) that I can select.

### CODE REVIEW

**Comment by brhou** [comment]
If it's just wrapping a model, would you be able to do it in a similar fashion to how Johnny did his pr? This might make it easier if we need to merge swagger-js changes in the future.

https://github.com/PagerDuty/swagger-ui/pull/17/files

**Comment by billkauf** [comment]
The problem is that `processModel` returns a lump of undifferentiated `<span>`s, all with largely the same class. This wraps it all in a `<span>` I can actually identify.

**Comment by steverice** [comment]
What is the `browser` directory for? Looks like a build artifact of some sort.

**Comment by steverice** [comment]
:+1:

**Comment by billkauf** [comment]
`browser` is build as a side-effect of running `grunt`. Seems to be part of their build/release process--for instance, https://github.com/swagger-api/swagger-js/commits/master/browser/swagger-client.js .

**Pull request merged**
